version: "3"

networks:
  web:
    external: true

services:
  traefik:
    image: traefik:v2.4
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/traefik_dynamic.toml:/traefik_dynamic.toml
      - $PWD/acme.json:/acme.json
    ports:
      - 80:80
      - 443:443