[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$zANZrBHM$AO3cIP5Rssj6vgWPEyBaW0"
  ]

[http.routers.api]
  rule = "Host(`traefik.nicoledepaula.adv.br`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"