version: '3'
services:
  letsencrypt:
    image: linuxserver/swag
    container_name: letsencrypt
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Sao_Paulo
      - URL=srvmail.nicoledepaula.adv.br
      - SUBDOMAINS=
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=diasnlucas@gmail.com
      - DHLEVEL=4096
    volumes:
      - ./config:/config
    restart: unless-stopped